language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_script:
  - cargo install diesel_cli || true

script:
  - echo "DATABASE_URL=test.db" > .env
  - diesel setup
  - cargo build
