language: rust

matrix:
  include:
    - rust: "stable"
      env: CARGO_FLAG="--no-default-features --features=with-syntex"
    - rust: "nightly"
      env: CARGO_FLAG=""

cache: cargo

script:
  - cargo install diesel_cli || true
  - echo "DATABASE_URL=$PWD/test.db" > .env
  - /home/travis/.cargo/bin/diesel setup
  - cargo build $CARGO_FLAG
